/**
 * Shared constants across frontend and backend
 */

export const API_VERSION = 'v1';

export const BLOG_CONSTRAINTS = {
  PROMPT_MIN_LENGTH: 3,
  PROMPT_MAX_LENGTH: 500,
  TARGET_WORD_COUNT: 1000,
  MAX_TOKENS: 2000,
};

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
};

export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_PROMPT: 'INVALID_PROMPT',
  GENERATION_FAILED: 'GENERATION_FAILED',
  MODEL_LOADING: 'MODEL_LOADING',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
};
